version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0

workflows:
  version: 2

  build_and_deploy_workflow:
    jobs:
      - build_and_deploy_job

  sonar_scan_workflow:
    jobs:
      - sonar_scan_job:
          context: SonarCloud

jobs:
  build_and_deploy_job:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm test -- --coverage --u
      - run: npm run build
      - run: npm run netlify:deploy

  sonar_scan_job:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm test -- --coverage --u
      - sonarcloud/scan
